version: "3"

tasks:
  re-*:
    vars:
      MACHINE: "{{index .MATCH 0}}"
    cmds:
      - sudo nixos-rebuild switch --flake .#{{.MACHINE}}
  debug-*:
    vars:
      MACHINE: "{{index .MATCH 0}}"
    cmds:
      - nixos-rebuild switch --flake .#{{.MACHINE}} --show-trace --verbose
  user:
    # vars:
    #   USERNAME: "{{index .MATCH 0}}"
    cmds:
      - home-manager switch --flake .#sagawao
  up:
    cmds:
      - nix flake update
  clean:
    cmds:
      - sudo nix profile wipe-history --profile /nix/var/nix/profiles/system --older-than 7d
  gc:
    cmds:
      - sudo nix-collect-garbage --delete-old
